name: Sync Files from External Repositories

on:
  schedule:
    - cron: '0 4 * * *'  # 每天4点 UTC时间触发
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the current repo (目标仓库)
    - name: Checkout the repository
      uses: actions/checkout@v3

    # Step 2: Clone the linkease/istore repository
    - name: Clone linkease/istore repository
      run: |
        git clone https://github.com/linkease/istore.git
        echo "Cloned linkease/istore repository"

    # Step 3: Clone the kenzok8/small-package repository
    - name: Clone kenzok8/small-package repository
      run: |
        git clone https://github.com/kenzok8/small-package.git
        echo "Cloned kenzok8/small-package repository"

    # Step 4: Run the shell script to organize files
    - name: Organize and Copy Files
      run: |
        chmod +x sync_files.sh  # 赋予执行权限
        .diy.sh  # 执行脚本
        echo "Files have been organized and copied into iStore"

    # Step 5: Debug: List the files in the 'iStore' directory to verify
    - name: List iStore directory contents
      run: |
        echo "Contents of iStore directory:"
        ls -R iStore

    # Step 6: Clean up old files (if any)
    - name: Clean up old files (if any)
      run: |
        git clean -fdx
        echo "Old files cleaned up"

    # Step 7: Commit the changes and push with GITHUB_TOKEN
    - name: Commit and Push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        # Check for file changes
        git status

        git add -A
        git status  # Show which files are staged for commit

        # If there are no changes, we won't commit anything
        git commit -m "Sync files from external repositories" || echo "No changes to commit"
        
        git push https://github.com/${{ github.repository }} HEAD:main
        echo "Changes pushed to the repository"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的默认 Token

    # Step 8: Clean up the cloned repositories
    - name: Clean up cloned repositories
      run: |
        rm -rf istore small-package
        echo "Cleaned up cloned repositories"
